# Generated by Django 4.0.3 on 2022-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Y', 'Есть в наличии'), ('N', 'Нет в наличии'), ('S', 'Не производится'), ('Z', 'Ожидается поступление')], default='Y', max_length=1),
        ),
    ]
