# Generated by Django 4.0.3 on 2022-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price_old_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
    ]
