# Generated by Django 4.0.3 on 2022-04-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('products', models.ManyToManyField(related_name='brands', to='main.product')),
            ],
        ),
    ]
