# Generated by Django 4.0.3 on 2022-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_twiceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiceproduct',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
