# Generated by Django 4.0.3 on 2022-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_twiceproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiceproduct',
            name='products',
            field=models.ManyToManyField(related_name='tw_product', to='main.product'),
        ),
    ]
