# Generated by Django 4.0.3 on 2022-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tel',
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
    ]
